lib/rumbl_web/router.ex
defmodule RumblWeb.Router do
  use RumblWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RumblWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RumblWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/session", SessionController, only: [:new, :create, :delete]
    get "/watch/:id", WatchController, :show
  end

  scope "/manage", RumblWeb do
    pipe_through [:browser, :authenticate_user]
    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", RumblWeb do
  #   pipe_through :api
  # end
end

lib/rumbl_web/views/layout_view.ex
defmodule RumblWeb.LayoutView do
  use RumblWeb, :view
end

lib/rumbl_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title><%= assigns[:page_title] || "Rumbl · Phoenix Framework" %></title>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
  <%= csrf_meta_tag() %>
</head>

<body class="bg-gray-200 relative h-screen overflow-x-hidden0">
  <header class="bg-indigo-700">
    <section class="container">
    <%= link "Rumbl", to: Routes.page_path(@conn, :index), class: "text-gray-300 font-black py-5 font-title tracking-wider text-5xl hover:text-white" %>

      <nav role="navigation" class="flex flex-wrap items-center content-between content-around">
        <%= if @current_user do%>
        <p class="text-gray-300 py-6 px-5 font-semibold"><%= @current_user.username %></p>
        <%= link "My Videos", to: Routes.video_path(@conn, :index), class: "bg-teal-400 hover:bg-teal-700 text-gray-300 hover:text-white font-bold py-2 px-5 rounded-full"%>
        <%= link "Log out", to: Routes.session_path(@conn, :delete, @current_user), method: "delete", class: "bg-teal-400 hover:bg-teal-700 text-gray-300 hover:text-white font-bold py-2 px-5 rounded-full" %>

        <% else %>
        <%= link "Register", to: Routes.user_path(@conn, :new), class: "bg-teal-400 hover:bg-teal-700 text-gray-300 hover:text-white font-bold py-2 px-5 rounded-full mr-6"%>
        <%= link "Log In", to: Routes.session_path(@conn, :new), class: "bg-teal-400 hover:bg-teal-700 text-gray-300 hover:text-white font-bold py-2 px-5 rounded-full"%>
        <% end %>
      </nav>
    </section>
  </header>

  <%= for {key, value} <- get_flash(@conn) do %>
  <%= if key == "info" do %>
  <div class="bg-green-400 mb-4">
    <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans">
      <%= value %>
    </div>
  </div>
  <% end%>
  <%= if key == "error" do %>
  <div class="bg-red-400 mb-4">
    <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans">
      <%= value %>
    </div>
  </div>
  <% end %>
  <%= if key == "message" do %>
  <div class="bg-blue-400 mb-4">
    <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans">
      <%= value %>
    </div>
  </div>
  <% end %>
  <% end %>

  <main role="main" class="container mt-6">
    <%= render @view_module, @view_template, assigns %>
  </main>
  <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</body>

</html>